site_name: SHCM RTD Playground
site_url: https://shcm-rtd-playground.readthedocs.io
site_description: readthedocs.io playground for testing
site_author: SHsuperCM

repo_url: https://github.com/SHsuperCM/ReadTheDocs

theme:
    name: mkdocs

nav:
    - Home: index.md

plugins:
    - search